### DISCUSSION TITLE
Raspberry Pi Issues

### DISCUSSION THREAD

**Discussion by bearded-papa** [Sanjeet990/Astroluma#60] [Q&A]
I have tried running via docker compose on my raspberry pi using both the docker compose example and the compose creator on the website but keep getting ```exec /usr/local/bin/docker-entrypoint.sh: exec format error``` in the logs for the app

**Comment by bearded-papa** [comment]
```yaml
services:
  app:
    image: sanjeet990/astroluma:latest
    container_name: astroluma
    # ports:
      # - "8758:8000"
    environment:
      PORT: 8758
      NODE_ENV: production
      SECRET_KEY: <REMOVED_KEY>
      MONGODB_URI: mongodb://mongodb:27017/astroluma
    volumes:
      - ./astroluma-app:/app/storage/uploads
    depends_on:
      - mongodb
    restart: always

  mongodb:
    image: mongo:4.0
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - ./astroluma-db:/data/db
    restart: always

volumes:
  mongo_data:
    driver: local
  uploads_data:
    driver: local
```
