### ISSUE TITLE
Can't reauthenticate after changing user sign on details

### ISSUE THREAD

**Issue by DruHoagland** [Sanjeet990/Astroluma#12]
Running into a bug with reauthentication. When I change the username + password of my default user, it doesn't persist on future login attempts. 

![Screenshot_20241210_113913](https://github.com/user-attachments/assets/739803db-69fc-4239-a4bb-fbe6de09afea)

The first time this happened I deleted + recreated the container and started setting up the app again. Then it happened again the next time I had to reauthenticate. 

Running this in Docker, and the logs indicate that MongoDB is connected & both containers working normally. I also tried the default credentials, new username + default password, default username + new password, no combo works. 

```
version: "3.8"
services:
  astroluma:
    image: sanjeet990/astroluma:latest
    container_name: astroluma
    environment:
      PORT: 5005
      NODE_ENV: production
      SECRET_KEY: $key
      MONGODB_URI: mongodb://192.168.1.85:27017/astroluma
    volumes:
      - /home/user/docker/astroluma/uploads:/app/storage/uploads
    depends_on:
      - mongodb
    restart: always
    network_mode: host
  mongodb:
    image: mongo:6.0
    container_name: astroluma_mongodb
    ports:
      - 27017:27017
    volumes:
      - /home/user/docker/astroluma/db:/data/db
    restart: unless-stopped
volumes:
  mongo_data:
    driver: local
  uploads_data:
    driver: local
networks:
  astroluna: {}
```
