### ISSUE TITLE
1.0.1 not working on Orange Pi 3 LTS arm64

### ISSUE THREAD

**Issue by janaxhell** [Sanjeet990/Astroluma#51]
**Describe the bug**
I had a working 1.0.0 build of Astroluma, I have updated to 1.0.1, it stopped working spitting an infinite loop of
`exec /usr/local/bin/docker-entrypoint.sh: exec format error`

**To Reproduce**
1. Just update to 1.0.1 using :latest

**Expected behavior**
To work fine

**Screenshots**

**Container logs:**
```
exec /usr/local/bin/docker-entrypoint.sh: exec format error
exec /usr/local/bin/docker-entrypoint.sh: exec format error
exec /usr/local/bin/docker-entrypoint.sh: exec format error
exec /usr/local/bin/docker-entrypoint.sh: exec format error
```

**Your docker-compose.yml content:**
If applicable, add your docker compose to better understand the problem.
```yaml
services:
  app:
    image: sanjeet990/astroluma:latest
    container_name: astroluma
    ports:
      - "8888:8000"
    environment:
      PORT: 8000
      NODE_ENV: production
      SECRET_KEY: ********************************
      MONGODB_URI: mongodb://192.168.1.168:27017/astroluma
    volumes:
      - /srv/dev-disk-by-uuid-aeae213f-8ce4-405c-9d96-db90e69c28f8/Config/astroluma/uploads_data:/app/storage/uploads
    depends_on:
      - mongodb
    restart: unless-stopped
    network_mode: host

  mongodb:
    image: mongo:4.0
    container_name: astroluma_mongodb
    ports:
      - "27017:27017"
    volumes:
      - /srv/dev-disk-by-uuid-aeae213f-8ce4-405c-9d96-db90e69c28f8/Config/astroluma/mongo_data:/data/db
    restart: unless-stopped
```

**Other details:**
 - Host CPU Type [e.g. x64]: arm64
 - Host OS [e.g. Ubuntu 22.04]: Armbian/OMV 7/Docker

**Additional context**
In previous build I had to change mongo: to 4.0, this time I've tried both 4.0 and 6.0 with no result.
