### ISSUE TITLE
Default Login Credentials wont work

### ISSUE THREAD

**Issue by DJKenzoDE** [Sanjeet990/Astroluma#53]
**Describe the bug**
Cant login with the default credentials

**To Reproduce**
deploy via docker with mongo v6 and v4

**Expected behavior**
login as admin but it show login failed

**Container logs:**
[astroluma.log](https://github.com/user-attachments/files/18240545/astroluma.log)

**Your docker-compose.yml content:**
If applicable, add your docker compose to better understand the problem.
```yaml

version: '3.8'
services:
  app:
    image: sanjeet990/astroluma:latest
    container_name: astroluma
    ports:
      - "8000:8000"
    environment:
      PORT: 8000
      NODE_ENV: production
      SECRET_KEY: a2c5f9a8b2d7e1a7f2c9c8d9b5f7a3d5
      MONGODB_URI: mongodb://mongodb:27017/astroluma
    volumes:
      - ./astroluma-app:/app/storage/uploads
    depends_on:
      - mongodb
    restart: always

  mongodb:
    image: mongo:4.0
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - ./astroluma-db:/data/db
    restart: always

volumes:
  mongo_data:
    driver: local
  uploads_data:
    driver: local

```

**Other details:**
 - Host CPU Type [e.g. x64]: x64
 - Host OS [e.g. Ubuntu 22.04]: ubuntu 22.04
