### ISSUE TITLE
Question: How do you delete uploads where the files were accidentally removed

### ISSUE THREAD

**Issue by jrobiii** [Sanjeet990/Astroluma#58]
**Describe the bug**

**To Reproduce**
- I have created volumes in the local folder for mongo_data and uploads_data

1. Add a new file listing and add an Icon (i.e. upload)
2. Go to the the docker-compose `uploads_folder` and remove the file(s)
3. Refresh the browser and go back to add a new file listing
4. Observe that there is still a "placeholder" for the upload, but it is the following icon (see **Screenshots**)

**Expected behavior**
I expected that since the files no longer existed that the "My Icons" would be empty.  I also could not find any way to remove previously uploads.

**Screenshots**
![image](https://github.com/user-attachments/assets/94ba40e5-d42f-4aa2-b576-158ad0e19967)

**Container logs:**
If applicable, add your container logs to better understand the problem.

**Your docker-compose.yml content:**
If applicable, add your docker compose to better understand the problem.

_Base docker-compose.yml_
```yaml
services:
  traefik:
    extends:
      file: ./traefik/docker-compose.yml
      service: traefik

  astroluma:
    extends:
      file: ./astroluma/docker-compose.yml
      service: astroluma

  astroluma_mongodb:
    extends:
      file: ./astroluma/docker-compose.yml
      service: astroluma_mongodb

  n8n:
    extends:
      file: ./n8n/docker-compose.yml
      service: n8n

  sysmon:
    extends:
      file: ./sysmon/docker-compose.yml
      service: uptimekuma

networks:
  traefik_net:
    name: traefik_net
  astroluma_network:
    name: astroluma_network

```
_astroluma/docker-compose.yml_
```yaml
services:
  astroluma:
    image: sanjeet990/astroluma:latest
    container_name: astroluma
    ports:
      - "8000:8000"
    environment:
      PORT: 8000
      NODE_ENV: production
      MONGODB_URI: mongodb://astroluma_mongodb:27017/astroluma
    volumes:
      - ./uploads_data:/astroluma/storage/uploads
    depends_on:
      - astroluma_mongodb
    restart: always
    networks:
      - traefik_net
      - astroluma_network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.astroluma.rule=Host(`homepage.domain.name`)"
      - "traefik.http.routers.astroluma.entrypoints=websecure"
      - "traefik.http.routers.astroluma.tls.certresolver=letsencrypt"
      - "traefik.http.services.astroluma.loadbalancer.server.port=8000"

  astroluma_mongodb:
    image: mongo:6.0
    container_name: astroluma_mongodb
    networks:
      - astroluma_network
    ports:
      - "27017:27017"
    volumes:
      - ./mongo_data:/data/db
    restart: always

volumes:
  mongo_data:
    driver: local
  uploads_data:
    driver: local
```

**Other details:**
 - Host CPU Type [e.g. x64]: x64
 - Host OS [e.g. Ubuntu 22.04]:  Ubuntu 24.04

**Additional context**
