### ISSUE TITLE
App integration not working?

### ISSUE THREAD

**Issue by schumi2004** [Sanjeet990/Astroluma#67]
**Describe the bug**
Did a fresh install with version 1.0.1 and when i configure Portainer and Proxmox app integration nothing changes/happens.
I'm also not getting any error's

p.s.: The Docker compose builder has some flaws regarding volumes.

**To Reproduce**
1. Fresh docker install
2. Login using default credentials
3. Configure App integration for both Proxmox and Portainer.
4. No error's seen

**Expected behavior**
Seeing the App integration icon are something else but nothing happens now.

**Screenshots**
Not much to show, the homepage does not change a single bit when adding these integrations.

**Container logs:**
`
> astroluma@1.0.0 server
> cd server && npm run server
> astrolumaserver@1.0.1 server
> node server.js
SERVER RUNNING AT 8000
Connected to MongoDB
No existing data found, proceeding with user seeding.
User collection cleared.
User data seeded successfully.
Initial links seeded successfully.
Selfh.st icon pack not found. Seeding selfh.st icon pack.
Selfh.st icon pack seeded successfully.
Data seeded successfully.
`

**Your docker-compose.yml content:**
If applicable, add your docker compose to better understand the problem.
```yaml
services:
  app:
    image: sanjeet990/astroluma:latest
    container_name: astroluma
    ports:
      - "8000:8000"
    environment:
      #PUID: 1000
      #PGID: 1000
      PORT: 8000
      NODE_ENV: production
      SECRET_KEY: a2c5f9a8b2d7e1a7f2c9c8d9b5f7a3d5
      MONGODB_URI: mongodb://mongodb:27017/astroluma
    volumes:
      - astroluma-app:/app/storage/uploads
    depends_on:
      - mongodb
    restart: unless-stopped
    networks:
      - proxy
    labels:
    # Watch container updates
      - wud.watch=true
      - wud.watch.digest=true
    # Traefik config
      - "traefik.enable=true"
      - "traefik.http.routers.astroluma.entrypoints=https"
      - "traefik.http.routers.astroluma.rule=Host(`astroluma.local.${DOMAINNAME_HS}`)"
      - "traefik.http.routers.astroluma.tls=true"
      - "traefik.http.routers.astroluma.service=astroluma"
      - "traefik.http.routers.astroluma.middlewares=internal@file"
      - "traefik.http.services.astroluma.loadbalancer.server.port=8000"
      - "traefik.docker.network=proxy"

  mongodb:
    image: mongo:6.0
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - astroluma-db:/data/db
    restart: unless-stopped
    networks:
      - proxy

volumes:
  astroluma-app:
    driver: local
  astroluma-db:
    driver: local

networks:
  proxy:
    external: true
```
