### ISSUE TITLE
Integration apps don't show stats

### ISSUE THREAD

**Issue by driftywinds** [Sanjeet990/Astroluma#89]
I have configured Portainer and Immich as my listings with their credentials and API keys provided to Astroluma, yet when I go to the Site Front they do not show their stats.

**Expected behavior**
The stats show up, using the API keys and credentials provided.

**Screenshots**

![Image](https://github.com/user-attachments/assets/73d28921-3761-415a-8640-777ec5f506b7)

**Other details:**
 - Host CPU Type [e.g. x64]: arm64
 - Host OS [e.g. Ubuntu 22.04]: Ubuntu 22 LTS

**Comment by Sanjeet990** [comment]
Thank you for trying Astroluma. When adding integration to tile, you have this Test Connection button, does it work? Test Connection helps you to findout if configurations are good and the service is reachable from the Dashboard BE. It also shares errors if any to identify you the issue. Can you please help with the logs?

![Image](https://github.com/user-attachments/assets/85f04ef8-477e-45ea-9ea9-160115dce296)

**Comment by driftywinds** [comment]
> Thank you for trying Astroluma. When adding integration to tile, you have this Test Connection button, does it work? Test Connection helps you to findout if configurations are good and the service is reachable from the Dashboard BE. It also shares errors if any to identify you the issue. Can you please help with the logs?
> 
> ![Image](https://github.com/user-attachments/assets/85f04ef8-477e-45ea-9ea9-160115dce296)

Yes, I have tested connections for each of them. Do you want me to share docker logs here?

**Comment by driftywinds** [comment]
[logs.txt](https://github.com/user-attachments/files/18485640/logs.txt)

These are the logs from the astroluma container

**Comment by darkcloud784** [comment]
> [logs.txt](https://github.com/user-attachments/files/18485640/logs.txt)
> 
> These are the logs from the astroluma container

Your log indicates it can't find or open the directory for the app storage. Make sure you have /app/storage/ mapped in your docker run or docker compose file.

**Comment by Sanjeet990** [comment]
As @darkcloud784 suggested, yes. looks like your apps storage is missing.

**Comment by driftywinds** [comment]
I should've attached my compose file, I have already bound the directory and this still occurs. Here's my compose file: - 
```
version: '3.8'
services:
  app:
    image: sanjeet990/astroluma:latest
    container_name: astroluma
    ports:
      - "3023:8000"
    environment:
      PORT: 3023
      NODE_ENV: production
      SECRET_KEY: z7xuzlkqrUtUiuhilnmN25e7hfaGWqzm
      MONGODB_URI: mongodb://localhost:27017/astroluma
    volumes:
      - ./astroluma-app:/app/storage/
    depends_on:
      - mongodb
    restart: always
    network_mode: host

  mongodb:
    image: mongo:6.0
    container_name: mongodb
    volumes:
      - ./astroluma-db:/data/db
    restart: always
    network_mode: host

volumes:
  mongo_data:
    driver: local
  uploads_data:
    driver: local
```

**Comment by driftywinds** [comment]
I should've attached my compose file, I have already bound the directory and this still occurs. Here's my compose file: - 
```
version: '3.8'
services:
  app:
    image: sanjeet990/astroluma:latest
    container_name: astroluma
#    ports:
#     - "3023:8000"
    environment:
      PORT: 3023
      NODE_ENV: production
      SECRET_KEY: <my secret key>
      MONGODB_URI: mongodb://localhost:27017/astroluma
    volumes:
      - ./astroluma-app:/app/storage/
    depends_on:
      - mongodb
    restart: always
    network_mode: host

  mongodb:
    image: mongo:6.0
    container_name: mongodb
    volumes:
      - ./astroluma-db:/data/db
    restart: always
    network_mode: host

volumes:
  mongo_data:
    driver: local
  uploads_data:
    driver: local
```
